<script lang="ts">
  import data from '$lib/changelog.json'
  import { SITE } from '$lib/site'

  interface Version {
    version: string
    tag: string
    date: string
    url: string
    compareUrl: string
    commits: { sha: string; short: string; subject: string; url: string }[]
  }

  /** Generated by scripts/changelog.mjs when a version is released. */
  const changelog: { repo: string; versions: Version[] } = data

  const date = (iso: string) =>
    new Date(`${iso}T12:00:00`).toLocaleDateString('es-VE', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    })
</script>

<svelte:head>
  <title>Novedades · Bllt inventario</title>
  <meta
    name="description"
    content="Qué cambió en cada versión de Bllt, con enlace a cada cambio."
  />
</svelte:head>

<main class="mx-auto max-w-3xl px-4 py-12">
  <h1 class="text-3xl font-semibold tracking-tight">Novedades</h1>
  <p class="text-muted-foreground mt-2">
    Los cambios de cada versión. Bllt se actualiza solo al abrirlo; también puedes
    <a class="text-primary underline-offset-4 hover:underline" href={SITE.download}
      >descargar la última</a
    >.
  </p>

  {#each changelog.versions as v (v.tag)}
    <section class="mt-10 border-t pt-8" id={v.tag}>
      <div class="flex flex-wrap items-baseline gap-x-3">
        <h2 class="text-xl font-semibold">
          <a class="hover:text-primary" href={v.url}>Versión {v.version}</a>
        </h2>
        <time class="text-muted-foreground text-sm" datetime={v.date}>{date(v.date)}</time>
      </div>
      <ul class="mt-4 space-y-2">
        {#each v.commits as c (c.sha)}
          <li class="flex gap-3 text-sm leading-relaxed">
            <a
              class="text-muted-foreground hover:text-primary shrink-0 font-mono text-xs leading-6"
              href={c.url}
              title="Ver el cambio en GitHub">{c.short}</a
            >
            <span>{c.subject}</span>
          </li>
        {/each}
      </ul>
      <a
        class="text-primary mt-4 inline-block text-sm underline-offset-4 hover:underline"
        href={v.compareUrl}>Ver todos los cambios</a
      >
    </section>
  {:else}
    <p class="text-muted-foreground mt-10 border-t pt-8">Aún no hay versiones publicadas.</p>
  {/each}
</main>
